[package]
name = "learning_axum_server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44.2", features = ["full"] }
axum = "0.8"
reqwest = "0.12.15"
anyhow = "1.0.98"
tower-http = { version = "0.6.2", features = ["full"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tracing = "0.1.41"
tower = "0.5.2"
 
