# Use mysql/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: app_db 
      POSTGRES_PASSWORD: welcome  


  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080